### ISSUE TITLE
Problems with the last steps

### ISSUE THREAD

**Issue by Namnodorel** [DemonWav/BukkitStart#1]
This is for InteliJ, right? I'm having problems with these steps:

> The run config should be a normal "Java Application" run config, with the following parameters:

    Main class: StartServer

I'm unable to find a place where I can specify a main class... The run config doesn't have that option. I also doubt that "StartServer" is explicit enough, usually you have to specify the whole classpath...

**Comment by DemonWav** [comment]
The run config looks like this.

![screen shot 2016-11-09 at 12 44 09 pm](https://cloud.githubusercontent.com/assets/1332104/20150211/4437324e-a67a-11e6-891f-8cad8efa771e.png)

It's just `StartServer`. It's in the default package.

**Comment by Namnodorel** [comment]
For me it looks like this:

http://puu.sh/scDSr/6c2e7aaa31.png

**Comment by DemonWav** [comment]
That's a Maven run config, not a Java Application run config.

**Comment by Namnodorel** [comment]
Ok, got it! I had to create an additional configuration of the type 'Application' insert the values there, make it execute the maven build first and then run with the Application config selected... Could've been a little more specific, but starting the server works now!

**Comment by jamierocks** [comment]
> Could've been a little more specific

Are you implying that the aforementioned photo[[1](https://github.com/DemonWav/BukkitStart/issues/1#issuecomment-259491856)] doesn't show `configuration of the type 'Application'`?

**Comment by Namnodorel** [comment]
It does, I was refering to the readme... It says "The run config should be a normal "Java Application" run config" which may be clear to someone using InteliJ often, but I came over from Eclipse not very long ago because I discovered InteliJ through Android Studio... I never had to work much with the build config, so it wasn't clear to me I'd need to create a new build "profile" of that type. What I would've expected would be a dropdown or a prompt where I can select the type, _without having to create anything new_.

**Comment by DemonWav** [comment]
Well this isn't an IntelliJ project, it works fine for IntelliJ or Eclipse. So the general instructions give enough info to setup either platform.
