### ISSUE TITLE
Hot swap not working

### ISSUE THREAD

**Issue by Namnodorel** [DemonWav/BukkitStart#2]
Aaaand I'm back, this time with a real issue ;)

Re-building and deploying the plugin/hotswapping doesn't work: The execution fails with the following exception:

Exception in thread "main" java.nio.file.FileAlreadyExistsException: .\plugins\plugin.jar
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:124)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1274)
	at StartServer.runServer(StartServer.java:68)
	at StartServer.main(StartServer.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

I guess you need to specify somewhere that you want to overwrite files if they exist already.

**Comment by Namnodorel** [comment]
The according code is

`        final File plugin = new File(pluginDir, "plugin.jar");

        //noinspection ResultOfMethodCallIgnored
        plugin.delete();
Files.copy(artifactJar.toPath(), plugin.toPath());`

I think this doesn't work, because plugin.jar is still being used by the server and thus cannot be deleted.

Also something I'd suggest for user convenience: Don't make the name of the file static, the project name would be a good filename for example.

**Comment by DemonWav** [comment]
You should be building with `Ctrl+F9` (make project) to hot-swap, not re-running the run configuration. The run config should be a singleton configuration, it should never be run concurrently.

**Comment by Namnodorel** [comment]
Hm, okay... I was used to hotswap using the build-button from Android Studio, but I'll do it the right way from now on! Maybe throw a more informative exception when the server is already running for people like me who otherwise post annoying issues? ;)

**Comment by DemonWav** [comment]
That's a good suggestion. I work with Android studio as well, so I know what you're referring to, but that's outside the scope of this project or the IntelliJ plugin. They change their build logic from a fundamental level to make that work.

**Comment by Namnodorel** [comment]
Not working with Make project either... 

I did the following: Create a dummy plugin and add a dummy command with the message output "abc". Started the server with it, ran the command, got the output - fine. Then I changed the message, hit Ctrl + F9 and entered the command again. Still the old message, even after a reload.

**Comment by Namnodorel** [comment]
Okay, finally everything works ^^ For a use in MinecraftDev it'll need some more documentation and more useful error messages for people like me ;)

**Comment by DemonWav** [comment]
I don't mean this to be rude at all, but no it doesn't. MinecraftDev is a tool for developers, and these are common things that experienced developers should know already. I'm not doing this to teach people how to use these tools, I'm doing it to provide the means necessary to use the tools more effectively. There are other projects that are more geared for the teaching aspect, but this isn't one of them.

**Comment by Namnodorel** [comment]
Well, then you'll have to deal with people like me who don't know these "common things"... I'm into Java (hobby) development for 2+ years now, and just never came across anyone mentioning such features. And why would I create a custom build config or use the debug mode if I don't need it (I actually tried the debug mode once or twice, but hadn't much time and didn't really figure out what it was supposed to do - I would've expected more inspector tools)? I originally came across MinecraftDev and BukkitStart, because I wanted to automate the process of building and deploying plugins to the server. Is that unexperienced?  The field of programming and programming tools is biiig, and you can never learn everything... And I just never needed to get that much into the building process of IDEs
